package com.localarena;

import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import android.content.*;import android.widget.*;import android.util.Log;

public class MainActivity extends Activity implements LocalNet.Listener{
 enum Screen{HOME,ROOM,PICKER,STORE,SETTINGS,CHESS,SEA,DURAK} Screen screen=Screen.HOME; LocalNet net; boolean host=false,connected=false; String ip=""; int me=0; String selectedGame=""; MonetizationState monetization=new MonetizationState(); ChessGame chess=new ChessGame(); SeaBattleGame sea=new SeaBattleGame(); DurakGame durak=new DurakGame(); ArenaView view;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(11,13,16));getWindow().setNavigationBarColor(Color.rgb(11,13,16));net=new LocalNet(new Handler(Looper.getMainLooper()),this);monetization.load(this);show(Screen.HOME);}
 void show(Screen s){screen=s;view=new ArenaView(this);setContentView(view);}
 void host(){host=true;me=0;ip=LocalNet.localIp();show(Screen.ROOM);net.host();}
 void join(String addr){if(addr==null||addr.trim().isEmpty()){Toast.makeText(this,"Введи IP хоста",Toast.LENGTH_SHORT).show();return;}host=false;me=1;ip=addr.trim();show(Screen.ROOM);net.join(ip);}
 void startGame(String g){try{if(g==null||(!g.equals("CHESS")&&!g.equals("SEA")&&!g.equals("DURAK")))return;selectedGame=g;if(g.equals("CHESS")){chess.reset();show(Screen.CHESS);}else if(g.equals("SEA")){sea.reset();sea.randomPlace(me,System.nanoTime());sea.ready[me]=true;show(Screen.SEA);net.send("SEA_READY|"+me+"|"+grid(sea.cells[me]));}else{durak.reset();show(Screen.DURAK);if(host)net.send("STATE|DURAK|"+durak.encodeFor(1));}}catch(Exception e){net.close();connected=false;screen=Screen.ROOM;view=new ArenaView(this);view.message="Ошибка запуска игры: "+e.getClass().getSimpleName();setContentView(view);}}
 String grid(int[][]g){StringBuilder s=new StringBuilder();for(int y=0;y<10;y++)for(int x=0;x<10;x++)s.append(g[y][x]);return s.toString();}
 boolean applyGrid(int p,String s){if(p<0||p>1||s==null||s.length()!=100)return false;int[][]g=new int[10][10];for(int y=0,k=0;y<10;y++)for(int x=0;x<10;x++){char ch=s.charAt(k++);if(ch!='0'&&ch!='1')return false;g[y][x]=ch-'0';}if(!sea.validFleet(g))return false;sea.cells[p]=g;sea.ready[p]=true;return true;}
 void broadcastSea(){net.send("STATE|SEA|"+sea.encodeFor(1));}
 void broadcastChess(){net.send("STATE|CHESS|"+chess.encode());}
 void broadcastDurak(){net.send("STATE|DURAK|"+durak.encodeFor(1));}
 @Override public void connected(boolean h,String address){connected=true;host=h;ip=address;if(view!=null)view.invalidate();}
 @Override public void status(String s){if(view!=null)view.message=s;view.invalidate();}
 @Override public void error(String e){connected=false;if(view!=null){view.message=e;view.invalidate();}}
 @Override public void line(String line){
  try{
   if(line.startsWith("GAME|")){String g=line.substring(5);if(g.equals("CHESS")||g.equals("SEA")||g.equals("DURAK"))startGame(g);return;}
   if(line.startsWith("SEA_READY|")){String[]a=line.split("\\|",-1);if(host&&a.length==3&&a[1].equals("1")&&a[2].length()==100&&applyGrid(1,a[2])){if(sea.ready[0]&&sea.ready[1])broadcastSea();}return;}
   if(line.startsWith("ACTION|")){if(!host)return;String[]a=line.split("\\|",-1);if(a.length<2)return;
    if(a[1].equals("CHESS")){if(a.length<4||!a[2].equals("1"))return;String[]m=a[3].split(",");if(m.length<2)return;int f=Integer.parseInt(m[0]),t=Integer.parseInt(m[1]);char pr=m.length>2&&!m[2].isEmpty()?m[2].charAt(0):0;if(!chess.white&&chess.move(new ChessGame.Move(f,t,pr)))broadcastChess();}
    else if(a[1].equals("SEA")){if(a.length<5||!a[2].equals("1"))return;int p=Integer.parseInt(a[2]),x=Integer.parseInt(a[3]),y=Integer.parseInt(a[4]);if(p==(sea.turn?0:1)&&sea.shoot(p,x,y))broadcastSea();}
    else if(a[1].equals("DURAK")){if(a.length<4||!a[3].equals("1"))return;if(handleDurak(a))broadcastDurak();}
    return;
   }
   if(line.startsWith("STATE|")){String[]a=line.split("\\|",3);if(a.length<3)return;if(a[1].equals("CHESS")){chess.decode(a[2]);show(Screen.CHESS);}else if(a[1].equals("SEA")){sea.decode(a[2]);show(Screen.SEA);}else if(a[1].equals("DURAK")){durak.decode(a[2]);show(Screen.DURAK);}}
  }catch(Exception ignored){}
 }
 boolean handleDurak(String[]a){try{String action=a[2];int p=Integer.parseInt(a[3]);if(action.equals("ATTACK"))return durak.addAttack(p,Integer.parseInt(a[4]));if(action.equals("DEFEND"))return durak.defend(p,Integer.parseInt(a[4]),Integer.parseInt(a[5]));if(action.equals("PASS"))return durak.passAttack(p);if(action.equals("TAKE"))return durak.take(p);}catch(Exception ignored){}return false;}
 void chessAction(int from,int to){if(chess.result!=' '||chess.white!=(me==0)||from<0||from>=64||to<0||to>=64)return;if(host){if(chess.move(new ChessGame.Move(from,to,(char)0)))broadcastChess();}else net.send("ACTION|CHESS|1|"+from+","+to+",");}
 void seaAction(int x,int y){if(sea.winner>=0||sea.turn!=(me==0)||!sea.ready[0]||!sea.ready[1])return;if(host){if(sea.shoot(me,x,y))broadcastSea();}else net.send("ACTION|SEA|1|"+x+"|"+y);}
 void durakAction(String action,int a,int b){if(host){if(handleDurak(new String[]{"ACTION","DURAK",action,String.valueOf(me),String.valueOf(a),String.valueOf(b)}))broadcastDurak();}else net.send("ACTION|DURAK|"+action+"|1|"+a+"|"+b);}
 @Override public void onBackPressed(){if(screen==Screen.HOME){super.onBackPressed();return;}if(screen==Screen.ROOM){net.close();connected=false;show(Screen.HOME);return;}if(screen==Screen.PICKER){show(Screen.ROOM);return;}if(screen==Screen.CHESS||screen==Screen.SEA||screen==Screen.DURAK){show(Screen.PICKER);return;}show(Screen.HOME);}@Override protected void onDestroy(){net.close();super.onDestroy();}
 final class ArenaView extends View{
  Paint p=new Paint(3);String message="Подготовка…";int sel=-1;float d;int bg=Color.rgb(11,13,16),panel=Color.rgb(22,25,31),text=Color.rgb(240,243,247),muted=Color.rgb(154,163,173);
  ArenaView(Context c){super(c);d=getResources().getDisplayMetrics().density;setBackgroundColor(bg);}
  void rect(Canvas c,float l,float t,float r,float b,int col,float rad){p.setColor(col);c.drawRoundRect(l,t,r,b,rad,rad,p);}void txt(Canvas c,String s,float x,float y,float size,int col){p.setTextSize(size*d);p.setColor(col);c.drawText(s,x,y,p);}void center(Canvas c,String s,float x,float y,float size,int col){p.setTextSize(size*d);p.setColor(col);c.drawText(s,x-p.measureText(s)/2,y,p);}
  void button(Canvas c,String s,float top,int col){float l=24*d,r=getWidth()-24*d,h=56*d;rect(c,l,top,r,top+h,col,18*d);center(c,s,getWidth()/2,top+35*d,16,Color.WHITE);}void miniButton(Canvas c,String s,float l,float top,float r,int col){rect(c,l,top,r,top+50*d,col,16*d);center(c,s,(l+r)/2,top+32*d,14,Color.WHITE);}
  protected void onDraw(Canvas c){super.onDraw(c);if(screen==Screen.HOME)home(c);else if(screen==Screen.ROOM)room(c);else if(screen==Screen.PICKER)picker(c);else if(screen==Screen.STORE)store(c);else if(screen==Screen.SETTINGS)settings(c);else if(screen==Screen.CHESS)chess(c);else if(screen==Screen.SEA)sea(c);else durak(c);}
  void header(Canvas c,String title,String sub){txt(c,"LOCALARENA",24*d,36*d,13,muted);txt(c,title,24*d,78*d,30,text);if(sub!=null)txt(c,sub,24*d,104*d,14,muted);}
  void home(Canvas c){header(c,"LOCALARENA","Локальный сборник настольных игр");button(c,"♟  Шахматы",140*d,Color.rgb(45,73,93));button(c,"⚓  Морской бой",208*d,Color.rgb(30,77,86));button(c,"♦  Дурак",276*d,Color.rgb(82,54,72));button(c,"＋  Создать комнату",360*d,Color.rgb(57,61,70));button(c,"↪  Войти в комнату",428*d,Color.rgb(48,67,76));button(c,"🛍  Магазин",496*d,Color.rgb(76,65,45));button(c,"⚙  Настройки",564*d,Color.rgb(48,52,58));}
  void room(Canvas c){header(c,host?"Комната создана":"Подключение","Порт "+LocalNet.PORT);rect(c,24*d,140*d,getWidth()-24*d,275*d,panel,20*d);txt(c,host?"IP для второго телефона":"IP хоста",48*d,174*d,14,muted);center(c,host?ip:"Ожидаю соединение…",getWidth()/2,225*d,24,text);txt(c,host?"Подключи второй телефон к этой сети.":"После подключения хост выберет игру.",48*d,255*d,13,muted);if(host&&connected)button(c,"Выбрать игру",320*d,Color.rgb(58,115,88));txt(c,message,24*d,420*d,14,muted);}
  void store(Canvas c){
header(c,"Магазин","Базовая версия уже полностью бесплатна.");
rect(c,24*d,135*d,getWidth()-24*d,285*d,panel,20*d);
txt(c,"💖 Поддержать автора",48*d,175*d,18,text);
txt(c,"Добровольная поддержка — любая сумма.",48*d,204*d,13,muted);
txt(c,"Платежи пока не подключены.",48*d,227*d,13,muted);
txt(c,"⭐ Premium",48*d,265*d,18,text);
txt(c,"Будущие скины, темы, эффекты и другие плюшки.",48*d,294*d,13,muted);
txt(c,"Без рекламы. Без ограничений.",48*d,320*d,13,Color.rgb(150,220,190));
button(c,"Скоро: контент и поддержка",345*d,Color.rgb(58,61,70));
button(c,"← Назад",415*d,Color.rgb(48,52,58));
}
void settings(Canvas c){header(c,"Настройки","Сохраняются на устройстве.");rect(c,24*d,135*d,getWidth()-24*d,255*d,panel,20*d);txt(c,"Тема интерфейса",48*d,175*d,16,text);txt(c,monetization.themeId,48*d,207*d,14,muted);txt(c,"Выбранный набор",48*d,235*d,16,text);txt(c,monetization.selectedSkinId,48*d,265*d,14,muted);button(c,"Сбросить локальные настройки",290*d,Color.rgb(76,55,55));button(c,"← Назад",360*d,Color.rgb(48,52,58));}
void picker(Canvas c){header(c,"Выбор игры",host?"Ты хост — выбери игру":"Хост выбирает игру");button(c,"♟  ШАХМАТЫ",150*d,Color.rgb(45,73,93));button(c,"⚓  МОРСКОЙ БОЙ",218*d,Color.rgb(30,77,86));button(c,"♦  ДУРАК",286*d,Color.rgb(82,54,72));}
  void chess(Canvas c){header(c,"Шахматы",chess.result==' '?"Твой цвет: "+(me==0?"белые":"чёрные"):(chess.result=='W'?"Победа белых":chess.result=='B'?"Победа чёрных":"Ничья"));float top=132*d,side=Math.min(getWidth()-32*d,getHeight()-top-70*d),cell=side/8,left=(getWidth()-side)/2;for(int y=0;y<8;y++)for(int x=0;x<8;x++){int bx=me==0?x:7-x,by=me==0?y:7-y;int s=ChessGame.sq(bx,by);p.setColor((x+y)%2==0?Color.rgb(230,221,201):Color.rgb(92,111,116));c.drawRect(left+x*cell,top+y*cell,left+(x+1)*cell,top+(y+1)*cell,p);if(s==sel){p.setColor(Color.rgb(105,175,145));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4*d);c.drawRect(left+x*cell+2*d,top+y*cell+2*d,left+(x+1)*cell-2*d,top+(y+1)*cell-2*d,p);p.setStyle(Paint.Style.FILL);}char pc=chess.b[s];if(pc!='.')center(c,piece(pc),left+x*cell+cell/2,top+y*cell+cell*.68f,cell*.62f,Character.isUpperCase(pc)?Color.WHITE:Color.rgb(25,28,31));}txt(c,chess.result==' '?"Выбери фигуру и клетку":"Партия завершена",24*d,top+side+35*d,15,muted);}
  String piece(char c){switch(c){case 'K':case 'k':return "♚";case 'Q':case 'q':return "♛";case 'R':case 'r':return "♜";case 'B':case 'b':return "♝";case 'N':case 'n':return "♞";default:return "♟";}}
  void sea(Canvas c){header(c,"Морской бой",sea.winner<0?(sea.turn==(me==0)?"Твой ход":"Ход соперника"):"Победитель: игрок "+(sea.winner+1));float top=135*d,gap=34*d,bottom=28*d,size=Math.min(getWidth()-48*d,(getHeight()-top-gap-bottom)/2f),cell=size/10,left=(getWidth()-size)/2,y=top;txt(c,"Твоя карта",left,y-12*d,13,muted);drawGrid(c,sea.cells[me],left,y,cell);float y2=y+size+gap;txt(c,"Поле огня",left,y2-10*d,13,muted);drawEnemy(c,sea.cells[1-me],left,y2,cell);}
  void drawGrid(Canvas c,int[][]g,float l,float t,float cell){for(int y=0;y<10;y++)for(int x=0;x<10;x++){int v=g[y][x],col=v==1?Color.rgb(68,91,106):v==2?Color.rgb(48,53,61):v==3?Color.rgb(191,80,78):Color.rgb(29,49,59);p.setColor(col);c.drawRect(l+x*cell,t+y*cell,l+(x+1)*cell-1,t+(y+1)*cell-1,p);}}
  void drawEnemy(Canvas c,int[][]g,float l,float t,float cell){for(int y=0;y<10;y++)for(int x=0;x<10;x++){int v=g[y][x],col=v==2?Color.rgb(48,53,61):v==3?Color.rgb(191,80,78):Color.rgb(29,49,59);p.setColor(col);c.drawRect(l+x*cell,t+y*cell,l+(x+1)*cell-1,t+(y+1)*cell-1,p);}}
  void durak(Canvas c){header(c,"Дурак",durak.finished?"Партия завершена":"Козырь: "+DurakGame.suitName(durak.trump));txt(c,"Твоя рука ("+durak.hand[me].size()+")",24*d,142*d,14,muted);float hw=Math.max(1,durak.hand[me].size());float w=Math.min(76*d,(getWidth()-48*d)/hw);for(int i=0;i<durak.hand[me].size();i++){int card=durak.hand[me].get(i);float x=24*d+i*w;rect(c,x,160*d,x+w-5*d,230*d,Color.rgb(242,242,236),10*d);center(c,DurakGame.card(card),x+w/2,202*d,15,Color.rgb(22,24,28));}txt(c,"Атака / защита",24*d,285*d,14,muted);for(int i=0;i<durak.attack.size();i++){float x=24*d+i*62*d;rect(c,x,300*d,x+54*d,375*d,Color.rgb(70,75,84),10*d);center(c,DurakGame.card(durak.attack.get(i)),x+27*d,332*d,14,Color.WHITE);if(i<durak.defense.size()&&durak.defense.get(i)>=0)txt(c,DurakGame.card(durak.defense.get(i)),x+8*d,360*d,12,Color.rgb(150,220,190));}txt(c,durak.finished?(durak.loser==DurakGame.NONE?"Ничья":durak.loser==me?"Ты проиграл":"Ты выиграл"):(durak.attacker==me?"Твой ход в атаке":"Ход соперника"),24*d,420*d,15,durak.finished?Color.rgb(240,210,150):durak.attacker==me?Color.rgb(150,220,190):muted);txt(c,"Козырь: "+DurakGame.suitName(durak.trump)+"   Колода: "+durak.deck.size(),24*d,445*d,13,muted);if(!durak.finished){miniButton(c,"Взять",24*d,465*d,getWidth()/2-6*d,Color.rgb(86,63,63));miniButton(c,"Бито / пас",getWidth()/2+6*d,465*d,getWidth()-24*d,Color.rgb(57,79,67));}}
  public boolean onTouchEvent(MotionEvent e){\n   if(e.getAction()==MotionEvent.ACTION_DOWN){edgeStartX=e.getX();edgeStartY=e.getY();return true;}\n   if(e.getAction()!=MotionEvent.ACTION_UP)return true;\n   float x=e.getX(),y=e.getY();\n   if(edgeStartX>=getWidth()-32*d && x<edgeStartX-80*d && Math.abs(y-edgeStartY)<140*d){edgeStartX=-1;edgeStartY=-1;navigateBack();return true;}\n   edgeStartX=-1;edgeStartY=-1;if(screen==Screen.HOME){if(y>135*d&&y<340*d)Toast.makeText(MainActivity.this,"Сначала создай или войди в комнату.",Toast.LENGTH_SHORT).show();else if(y>350*d&&y<420*d)host();else if(y>420*d&&y<490*d){final EditText q=new EditText(MainActivity.this);q.setHint("192.168.43.1");new AlertDialog.Builder(MainActivity.this).setTitle("Войти в комнату").setView(q).setPositiveButton("Подключиться",(z,w)->join(q.getText().toString())).setNegativeButton("Отмена",null).show();}if(y>490*d&&y<555*d){show(Screen.STORE);}else if(y>555*d&&y<630*d){show(Screen.SETTINGS);}return true;}if(screen==Screen.ROOM){if(host&&connected&&y>315*d&&y<390*d)show(Screen.PICKER);return true;}if(screen==Screen.STORE||screen==Screen.SETTINGS){if(screen==Screen.SETTINGS&&y>280*d&&y<355*d){monetization.reset(MainActivity.this);show(Screen.SETTINGS);}else if(y>350*d&&y<440*d){show(Screen.HOME);}return true;}if(screen==Screen.PICKER&&host){if(y>140*d&&y<215*d){net.send("GAME|CHESS");startGame("CHESS");}else if(y>215*d&&y<285*d){net.send("GAME|SEA");startGame("SEA");}else if(y>285*d&&y<360*d){net.send("GAME|DURAK");startGame("DURAK");}return true;}if(screen==Screen.CHESS){float top=132*d,side=Math.min(getWidth()-32*d,getHeight()-top-70*d),cell=side/8,left=(getWidth()-side)/2;if(x>=left&&x<=left+side&&y>=top&&y<=top+side&&chess.result==' '){int vx=(int)((x-left)/cell),vy=(int)((y-top)/cell);int bx=me==0?vx:7-vx,by=me==0?vy:7-vy,sq=ChessGame.sq(bx,by);if(sel<0){if(ChessGame.side(chess.b[sq],chess.white==(me==0)))sel=sq;}else{chessAction(sel,sq);sel=-1;}}return true;}if(screen==Screen.SEA){float size=Math.min(getWidth()-48*d,getHeight()/2.8f),cell=size/10,left=(getWidth()-size)/2,y2=135*d+size+55*d;if(x>=left&&x<=left+size&&y>=y2&&y<=y2+size)seaAction((int)((x-left)/cell),(int)((y-y2)/cell));return true;}if(screen==Screen.DURAK){if(durak.finished)return true;float hw=Math.max(1,durak.hand[me].size());float w=Math.min(76*d,(getWidth()-48*d)/hw);if(y>=160*d&&y<=240*d){int i=(int)((x-24*d)/w);if(i>=0&&i<durak.hand[me].size()){int c=durak.hand[me].get(i);if(durak.defender==me){int idx=0;while(idx<durak.defense.size()&&durak.defense.get(idx)>=0)idx++;if(idx<durak.attack.size())durakAction("DEFEND",c,idx);}else durakAction("ATTACK",c,-1);}}else if(y>465*d&&y<525*d){if(durak.defender==me)durakAction("TAKE",0,0);else if(durak.attacker==me)durakAction("PASS",0,0);}return true;}return true;}
 }
}
