package com.localarena;

import java.util.*;

final class SeaBattleGame {
    int[][][] cells={new int[10][10],new int[10][10]}; boolean[] ready={false,false}; boolean turn=true; int winner=-1;
    SeaBattleGame(){reset();}
    void reset(){cells=new int[][][]{new int[10][10],new int[10][10]};ready[0]=ready[1]=false;turn=true;winner=-1;}
    void randomPlace(int p,long seed){Random r=new Random(seed);int[] lengths={4,3,3,2,2,2,1,1,1,1};for(int restart=0;restart<200;restart++){cells[p]=new int[10][10];boolean all=true;for(int len:lengths){boolean ok=false;for(int tries=0;tries<1200&&!ok;tries++){int x=r.nextInt(10),y=r.nextInt(10);boolean h=r.nextBoolean();if(h&&x+len>10)continue;if(!h&&y+len>10)continue;boolean good=true;for(int i=0;i<len;i++){int xx=x+(h?i:0),yy=y+(h?0:i);for(int dx=-1;dx<=1;dx++)for(int dy=-1;dy<=1;dy++){int nx=xx+dx,ny=yy+dy;if(nx>=0&&nx<10&&ny>=0&&ny<10&&cells[p][ny][nx]==1)good=false;}}if(good){for(int i=0;i<len;i++)cells[p][y+(h?0:i)][x+(h?i:0)]=1;ok=true;}}if(!ok){all=false;break;}}if(all&&validFleet(cells[p]))return;}throw new IllegalStateException("Unable to place fleet");}
    boolean validFleet(int[][]g){if(g==null||g.length!=10)return false;for(int[]row:g)if(row==null||row.length!=10)return false;boolean[][]seen=new boolean[10][10];int[]count={0,0,0,0,0};for(int y=0;y<10;y++)for(int x=0;x<10;x++)if(g[y][x]==1&&!seen[y][x]){int n=0,minX=x,maxX=x,minY=y,maxY=y;ArrayDeque<int[]>q=new ArrayDeque<>();q.add(new int[]{x,y});seen[y][x]=true;while(!q.isEmpty()){int[]v=q.remove();n++;minX=Math.min(minX,v[0]);maxX=Math.max(maxX,v[0]);minY=Math.min(minY,v[1]);maxY=Math.max(maxY,v[1]);for(int[]d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){int nx=v[0]+d[0],ny=v[1]+d[1];if(nx>=0&&nx<10&&ny>=0&&ny<10&&g[ny][nx]==1&&!seen[ny][nx]){seen[ny][nx]=true;q.add(new int[]{nx,ny});}}}if(n>4||((maxX-minX)>0&&(maxY-minY)>0))return false;if(n>=1)count[n]++;for(int yy=Math.max(0,minY-1);yy<=Math.min(9,maxY+1);yy++)for(int xx=Math.max(0,minX-1);xx<=Math.min(9,maxX+1);xx++)if(g[yy][xx]==1&&!(xx>=minX&&xx<=maxX&&yy>=minY&&yy<=maxY))return false;}return count[4]==1&&count[3]==2&&count[2]==3&&count[1]==4;}
    boolean shoot(int shooter,int x,int y){if(winner>=0||!ready[0]||!ready[1]||shooter!=(turn?0:1)||x<0||x>9||y<0||y>9)return false;int[][]target=cells[1-shooter];if(target[y][x]==2||target[y][x]==3)return false;if(target[y][x]==1){target[y][x]=3;if(allSunk(target))winner=shooter;}else{target[y][x]=2;turn=!turn;}return true;}
    boolean allSunk(int[][]g){for(int[]row:g)for(int c:row)if(c==1)return false;return true;}
    String encode(){return encodeFor(0);}
    String encodeFor(int viewer){StringBuilder s=new StringBuilder();s.append(turn?'0':'1').append(',').append(winner).append(',').append(ready[0]?'1':'0').append(',').append(ready[1]?'1':'0');for(int p=0;p<2;p++){s.append('|');for(int y=0;y<10;y++)for(int x=0;x<10;x++){int v=cells[p][y][x];if(p!=viewer&&v==1)v=0;s.append(v);}}return s.toString();}
    void decode(String s){String[]a=s.split("\\|",-1);if(a.length!=3)throw new IllegalArgumentException("Invalid sea state sections");String[]h=a[0].split(",");if(h.length!=4)throw new IllegalArgumentException("Invalid sea state header");int newWinner=Integer.parseInt(h[1]);boolean newTurn=h[0].equals("0");boolean r0=h[2].equals("1"),r1=h[3].equals("1");int[][][]next=new int[2][10][10];for(int p=0;p<2;p++){String q=a[p+1];if(q.length()!=100)throw new IllegalArgumentException("Invalid sea grid length");int k=0;for(int y=0;y<10;y++)for(int x=0;x<10;x++){char ch=q.charAt(k++);if(ch<'0'||ch>'3')throw new IllegalArgumentException("Invalid sea cell");next[p][y][x]=ch-'0';}}cells=next;turn=newTurn;winner=newWinner;ready[0]=r0;ready[1]=r1;}
}
